spring:
  profiles:
    active: prod
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
logging:
  level:
    com.ucinae.root: debug